-- ============================================================================
-- MASTER SUPABASE SCHEMA FOR HOMEGROUND
-- ============================================================================
-- This script is "idempotent", meaning you can run it multiple times safely.
-- It ensures ALL required columns exist.

-- 1. Ensure the 'matches' table exists
CREATE TABLE IF NOT EXISTS public.matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

-- 2. Add All Columns Required by App Type Definitions
-- We use 'ADD COLUMN IF NOT EXISTS' so this works even if you already have the table.

-- --- Identifiers ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS match_id text;         -- String: "match_ timestamp..."
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS match_code text;       -- String: "1234" (4 digits)
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS series_id text;        -- String: Optional Series ID
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS tournament_id text;    -- String: Optional Tournament ID

-- --- Configuration ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS match_type text;       -- "Single", "Series", "Tournament"
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS team_size integer;     -- Number of players per team
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS overs_per_innings integer;

-- --- Game State (Crucial for Live Scoring) ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS current_innings integer; -- 1 or 2
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS current_over integer DEFAULT 0;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS current_ball integer DEFAULT 0;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS status text DEFAULT 'live';

-- --- Active Players (Crucial for "Start Innings" / "Next Over") ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS striker text;          -- Player ID
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS non_striker text;      -- Player ID
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS current_bowler text;   -- Player ID

-- --- Complex Data (Stored as JSON) ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS team1 JSONB;           -- Full Team Object
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS team2 JSONB;           -- Full Team Object
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS toss JSONB;            -- { winnerId, batFirstId }
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS innings1 JSONB;        -- Stats for inn 1
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS innings2 JSONB;        -- Stats for inn 2
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS history JSONB DEFAULT '[]'::jsonb; -- Ball-by-ball array
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS man_of_match JSONB;

-- --- Results & Timestamps ---
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS result text;           -- "Team 1 won by..."
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS winner text;           -- Team ID
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS expires_at timestamptz;

-- 3. Enable Row Level Security (Review based on your needs)
-- For development/public access, we usually default to allowing public access,
-- but standard practice involves policies.
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Allow public read/write (Modify if you have auth set up)
CREATE POLICY "Enable read access for all users" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.matches FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.matches FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.matches FOR DELETE USING (true);

