-- ============================================================================
-- FRESH START SCRIPT (NUCLEAR OPTION)
-- This will DELETE your existing matches table and create a perfect new one.
-- ALL EXISTING MATCH DATA WILL BE LOST (as you requested to start fresh).
-- ============================================================================

-- 1. DROP EXISTING TABLE
DROP TABLE IF EXISTS public.matches CASCADE;

-- 2. CREATE TABLE WITH ALL COLUMNS
CREATE TABLE public.matches (
  -- Primary Keys and IDs
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id text NOT NULL,
  match_code text NOT NULL,
  series_id text,
  tournament_id text,

  -- Configuration
  match_type text,
  team_size integer,
  overs_per_innings integer,

  -- Game State
  status text DEFAULT 'live', -- 'live', 'completed', 'scheduled'
  current_innings integer DEFAULT 1,
  current_over integer DEFAULT 0,
  current_ball integer DEFAULT 0,

  -- Active Players (The ones causing your bug!)
  striker text,
  non_striker text,
  current_bowler text,

  -- Teams & Data (Stored as JSON for flexibility)
  team1 JSONB,
  team2 JSONB,
  toss JSONB,
  innings1 JSONB,
  innings2 JSONB,
  history JSONB DEFAULT '[]'::jsonb, -- Ball-by-ball history
  man_of_match JSONB,

  -- Results
  result text,
  winner text,

  -- Timestamps
  created_at timestamptz DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz
);

-- 3. ENABLE SECURITY (RLS)
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- 4. CREATE OPEN POLICIES (Read/Write for Everyone)
CREATE POLICY "Enable all access" ON public.matches FOR ALL USING (true) WITH CHECK (true);

-- 5. CREATE INDEXES (For Performance)
CREATE INDEX idx_match_code ON public.matches(match_code);
CREATE INDEX idx_status ON public.matches(status);
